
server:
  port: 8081
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://172.16.82.42:61616
    pool:
      enabled: true
      max-connections: 10

queueName: publish.queue
topicName: publish.topic

---

spring:
  dubbo:
    application:
      name: service-provider
    base-package: com.producer.service # dubbo服务发布者所在的包
    registry:
      address: 172.16.82.42 # zookeeper注册中心的地址
      port: 2181       # zookeeper注册中心的端口
      protocol: zookeeper
      register: true
    protocol:
      name: dubbo
      port: 20880
      accesslog: true
    provider:
      retries: 1
      delay: -1


